* Ubuntu packaging

Debian / Ubuntu tooling like dpkg-buildpackage would require the location of the =debian/= directory be identical to upstream, which makes it impossible for me to describe my changes or write down how to do stuff. So:

- Because I want the top level README to exist and for top level to be able to contain packaging for other distros, it has to be at least one subdirectory deep.
  - Also because I want the produced files to stay within the repository, even if git-ignored.
- And because I want this README to exist, it needs to be another subdirectory deep.

Hence the =debian/= directory existing as =:/ubuntu/src/debian=.

** Building

#+begin_src sh
make build
#+end_src

** Publishing

After building

#+begin_src sh
dput ppa:kisaragi-hiu/taigikeyboard <.changes>
#+end_src

** Making a new package revision

Write a new entry at =src/debian/changelog=, then

#+begin_src sh
make clean
#+end_src

, then rebuild and reupload. I wrote the =clean= target to only clean within =src/= which allows preserving the original tar files (to avoid extra downloads) and previous built package files.

** Updating to a new upstream version

I'm not sure.

It's probably uscan, write a new entry, make sure it builds locally (fix patches), then rebuild + reupload. But a new upstream version hasn't happened yet so I haven't done this yet.
